name: ServerPlugin
version: '${project.version}'
main: com.burchard36.cloudlite.ServerPlugin
api-version: 1.19
depend:
  - HeadDatabase
commands:
  skipsong:
    aliases:
      - songskip
      - skip
      - nextsong
      - songnext
    description: "Skips you to the next song in queue"
  musicgui:
    aliases:
      - music
      - musicgui
      - songs
      - songlist
      - songgui
      - songui
    description: "Displays the Songs GUI"